builds:
  - main: ./cmd/terraform-demux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

brews:
  - tap:
      owner: etsy
      name:  terraform-demux

    folder:      Formula
    skip_upload: true

    homepage:    https://github.com/etsy/terraform-demux
    description: A user-friendly launcher (à la Bazelisk) for Terraform.
    license:     "Apache-2.0"

    conflicts:
      - "terraform"

    install: |
      bin.install "terraform-demux"
      bin.install_symlink bin/"terraform-demux" => "terraform"
