# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformDemux < Formula
  desc "A user-friendly launcher (à la Bazelisk) for Terraform."
  homepage "https://github.com/etsy/terraform-demux"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/etsy/terraform-demux/releases/download/v1.1.1/terraform-demux_1.1.1_darwin_arm64.tar.gz"
      sha256 "bac68916f3bc57775720c24e1892246fee8bc92cd1b72be4c744798438e5c4c5"

      def install
        bin.install "terraform-demux"
        bin.install_symlink bin/"terraform-demux" => "terraform"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/etsy/terraform-demux/releases/download/v1.1.1/terraform-demux_1.1.1_darwin_amd64.tar.gz"
      sha256 "bcb69b965679e7de9edf3266f45fe99ed451f8b789d97886ab63b1b35833cba3"

      def install
        bin.install "terraform-demux"
        bin.install_symlink bin/"terraform-demux" => "terraform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/etsy/terraform-demux/releases/download/v1.1.1/terraform-demux_1.1.1_linux_arm64.tar.gz"
      sha256 "1e714646b462fa44d953afed20dafd4d2b5af16aa473fa63315b203d43c1a085"

      def install
        bin.install "terraform-demux"
        bin.install_symlink bin/"terraform-demux" => "terraform"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/etsy/terraform-demux/releases/download/v1.1.1/terraform-demux_1.1.1_linux_amd64.tar.gz"
      sha256 "e684c53ce38f93d946be91ae7f88d9c2146a1c386cebcb1ef11c3389413597e8"

      def install
        bin.install "terraform-demux"
        bin.install_symlink bin/"terraform-demux" => "terraform"
      end
    end
  end

  conflicts_with "terraform"
end
