# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformDemux < Formula
  desc "A user-friendly launcher (à la Bazelisk) for Terraform."
  homepage "https://github.com/etsy/terraform-demux"
  version "2.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/etsy/terraform-demux/releases/download/v2.1.0/terraform-demux_2.1.0_darwin_amd64.tar.gz"
      sha256 "867b9252ea1b31b3aa12bbba1fba6953f552c49f5c410601f9857f4e9a28eb8f"

      def install
        bin.install "terraform-demux"
        bin.install_symlink bin/"terraform-demux" => "terraform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/etsy/terraform-demux/releases/download/v2.1.0/terraform-demux_2.1.0_darwin_arm64.tar.gz"
      sha256 "ba8306fd2c4031be48492d87da2aaec051634d050eb07b1753cf37ab55d98ed2"

      def install
        bin.install "terraform-demux"
        bin.install_symlink bin/"terraform-demux" => "terraform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/etsy/terraform-demux/releases/download/v2.1.0/terraform-demux_2.1.0_linux_arm64.tar.gz"
      sha256 "6110a08b8feeedf90948f574c9b88ef8048aa411ee420f24dfa77d1e98f1430f"

      def install
        bin.install "terraform-demux"
        bin.install_symlink bin/"terraform-demux" => "terraform"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/etsy/terraform-demux/releases/download/v2.1.0/terraform-demux_2.1.0_linux_amd64.tar.gz"
      sha256 "dd2a3d8642deb07731adee2baaa57a3780b3c251c7d1bc3f713fb0330427a0e1"

      def install
        bin.install "terraform-demux"
        bin.install_symlink bin/"terraform-demux" => "terraform"
      end
    end
  end

  conflicts_with "terraform"
end
